/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.16
 * Generated at: 2026-04-08 10:33:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_002dservices_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/tryeno_team/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("file:/Users/tryeno_team/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1664453510000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 final String c = request.getContextPath(); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Admin - Services Management</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    :root {\n");
      out.write("      --admin-primary: #5a67d8;\n");
      out.write("      --admin-accent: #7c3aed;\n");
      out.write("      --admin-bg: #f3f5fb;\n");
      out.write("      --admin-text: #0f172a;\n");
      out.write("      --admin-muted: #64748b;\n");
      out.write("      --admin-card-border: #e2e8f0;\n");
      out.write("      --admin-card-shadow: 0 10px 28px rgba(15, 23, 42, 0.08);\n");
      out.write("    }\n");
      out.write("    body {\n");
      out.write("      background: var(--admin-bg);\n");
      out.write("      color: var(--admin-text);\n");
      out.write("    }\n");
      out.write("    .navbar-admin {\n");
      out.write("      background: linear-gradient(135deg, var(--admin-primary) 0%, var(--admin-accent) 100%);\n");
      out.write("      box-shadow: 0 8px 18px rgba(90, 103, 216, 0.2);\n");
      out.write("    }\n");
      out.write("    .admin-layout {\n");
      out.write("      min-height: calc(100vh - 56px);\n");
      out.write("    }\n");
      out.write("    .page-header {\n");
      out.write("      margin-bottom: 0.8rem;\n");
      out.write("    }\n");
      out.write("    .page-title {\n");
      out.write("      font-weight: 700;\n");
      out.write("      letter-spacing: -0.02em;\n");
      out.write("      margin-bottom: 0.2rem;\n");
      out.write("    }\n");
      out.write("    .page-subtitle {\n");
      out.write("      color: var(--admin-muted);\n");
      out.write("      margin: 0;\n");
      out.write("      font-size: 0.95rem;\n");
      out.write("    }\n");
      out.write("    .sidebar {\n");
      out.write("      background: #111827;\n");
      out.write("      color: #cbd5e1;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      padding: 1rem;\n");
      out.write("      position: sticky;\n");
      out.write("      top: 1rem;\n");
      out.write("      box-shadow: 0 16px 28px rgba(2, 6, 23, 0.2);\n");
      out.write("    }\n");
      out.write("    @media (min-width: 992px) {\n");
      out.write("      .sidebar {\n");
      out.write("        min-height: calc(100vh - 2rem);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    .sidebar-title {\n");
      out.write("      color: #f8fafc;\n");
      out.write("      font-weight: 700;\n");
      out.write("      font-size: 0.95rem;\n");
      out.write("      margin-bottom: 0.75rem;\n");
      out.write("    }\n");
      out.write("    .sidebar .nav-link {\n");
      out.write("      color: #cbd5e1;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      padding: 0.55rem 0.7rem;\n");
      out.write("      margin-bottom: 0.2rem;\n");
      out.write("      font-size: 0.92rem;\n");
      out.write("      min-height: 52px;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("    .sidebar .nav-link:hover {\n");
      out.write("      background: rgba(255, 255, 255, 0.08);\n");
      out.write("      color: #fff;\n");
      out.write("    }\n");
      out.write("    .sidebar .nav-link.active {\n");
      out.write("      background: linear-gradient(135deg, var(--admin-primary), var(--admin-accent));\n");
      out.write("      color: #fff;\n");
      out.write("      font-weight: 600;\n");
      out.write("    }\n");
      out.write("    .sidebar .nav-link.disabled {\n");
      out.write("      opacity: 0.6;\n");
      out.write("      cursor: not-allowed;\n");
      out.write("    }\n");
      out.write("    .admin-card {\n");
      out.write("      border: 1px solid var(--admin-card-border);\n");
      out.write("      border-radius: 14px;\n");
      out.write("      box-shadow: var(--admin-card-shadow);\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("    .admin-card .card-header {\n");
      out.write("      background: #fff;\n");
      out.write("      border-bottom: 1px solid var(--admin-card-border);\n");
      out.write("      padding: 0.85rem 1rem;\n");
      out.write("      font-size: 0.95rem;\n");
      out.write("    }\n");
      out.write("    .admin-card .card-body {\n");
      out.write("      background: #fff;\n");
      out.write("    }\n");
      out.write("    .form-shell {\n");
      out.write("      border: 1px solid #e2e8f0;\n");
      out.write("      border-radius: 12px;\n");
      out.write("      background: linear-gradient(180deg, #ffffff 0%, #fcfdff 100%);\n");
      out.write("      padding: 0.9rem;\n");
      out.write("    }\n");
      out.write("    .form-section {\n");
      out.write("      border: 1px solid #e7ecf5;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      background: #f8fafc;\n");
      out.write("      padding: 0.75rem;\n");
      out.write("      margin-bottom: 0.75rem;\n");
      out.write("    }\n");
      out.write("    .form-section-title {\n");
      out.write("      font-size: 0.73rem;\n");
      out.write("      font-weight: 700;\n");
      out.write("      color: #475569;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("      letter-spacing: 0.03em;\n");
      out.write("      margin-bottom: 0.55rem;\n");
      out.write("    }\n");
      out.write("    .admin-label {\n");
      out.write("      font-size: 0.78rem;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("      letter-spacing: 0.02em;\n");
      out.write("      color: #475569;\n");
      out.write("      font-weight: 700;\n");
      out.write("      margin-bottom: 0.3rem;\n");
      out.write("    }\n");
      out.write("    .admin-help {\n");
      out.write("      color: #64748b;\n");
      out.write("      font-size: 0.76rem;\n");
      out.write("      font-weight: 500;\n");
      out.write("      text-transform: none;\n");
      out.write("      letter-spacing: 0;\n");
      out.write("    }\n");
      out.write("    .form-control {\n");
      out.write("      border-color: #dbe2ef;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      min-height: 38px;\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("      box-shadow: none;\n");
      out.write("    }\n");
      out.write("    textarea.form-control {\n");
      out.write("      min-height: auto;\n");
      out.write("    }\n");
      out.write("    .form-control:focus {\n");
      out.write("      border-color: #8b99ff;\n");
      out.write("      box-shadow: 0 0 0 3px rgba(90, 103, 216, 0.15);\n");
      out.write("    }\n");
      out.write("    .btn-admin-primary {\n");
      out.write("      border: none;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      padding: 0.62rem 0.9rem;\n");
      out.write("      font-weight: 600;\n");
      out.write("      background: linear-gradient(135deg, var(--admin-primary), var(--admin-accent));\n");
      out.write("      box-shadow: 0 8px 18px rgba(92, 87, 232, 0.25);\n");
      out.write("    }\n");
      out.write("    .btn-admin-primary:hover {\n");
      out.write("      filter: brightness(1.03);\n");
      out.write("    }\n");
      out.write("    .btn-admin-primary:disabled {\n");
      out.write("      opacity: 0.9;\n");
      out.write("    }\n");
      out.write("    .save-hint {\n");
      out.write("      font-size: 0.74rem;\n");
      out.write("      color: #64748b;\n");
      out.write("      text-align: center;\n");
      out.write("      margin-top: 0.55rem;\n");
      out.write("    }\n");
      out.write("    .admin-table thead th {\n");
      out.write("      background: #f8fafc;\n");
      out.write("      color: #334155;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("      letter-spacing: 0.02em;\n");
      out.write("      font-size: 0.75rem;\n");
      out.write("      font-weight: 700;\n");
      out.write("      padding-top: 0.75rem;\n");
      out.write("      padding-bottom: 0.75rem;\n");
      out.write("      white-space: nowrap;\n");
      out.write("    }\n");
      out.write("    .admin-table td {\n");
      out.write("      color: #1e293b;\n");
      out.write("      padding-top: 0.7rem;\n");
      out.write("      padding-bottom: 0.7rem;\n");
      out.write("      vertical-align: middle;\n");
      out.write("    }\n");
      out.write("    .service-img {\n");
      out.write("      width: 56px;\n");
      out.write("      height: 42px;\n");
      out.write("      object-fit: cover;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      border: 1px solid #e2e8f0;\n");
      out.write("      background: #f8fafc;\n");
      out.write("    }\n");
      out.write("    .empty-state {\n");
      out.write("      text-align: center;\n");
      out.write("      color: #64748b;\n");
      out.write("      padding: 1.2rem;\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-dark navbar-admin\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <span class=\"navbar-brand mb-0 h1\">Easy 2 Work Admin Portal</span>\n");
      out.write("    <div>\n");
      out.write("      <a class=\"btn btn-sm btn-light\" href=\"");
      out.print( c );
      out.write("/logout\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"container-fluid py-4 px-3 px-md-4 admin-layout\">\n");
      out.write("  <div class=\"page-header\">\n");
      out.write("    <h1 class=\"h4 page-title\">Service Management</h1>\n");
      out.write("    <p class=\"page-subtitle\">Create and maintain the services shown to customers.</p>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"row g-3\">\n");
      out.write("    <div class=\"col-12 col-lg-3 col-xl-2\">\n");
      out.write("      <aside class=\"sidebar\">\n");
      out.write("        <div class=\"sidebar-title\">Admin Menu</div>\n");
      out.write("        <nav class=\"nav flex-column\">\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/dashboard\">Dashboard</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/users\">User Management</a>\n");
      out.write("          <a class=\"nav-link active\" href=\"");
      out.print( c );
      out.write("/services\">Service Add / Manage</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/reviews\">Reviews</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/settings\">Settings</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/logout\">Logout</a>\n");
      out.write("        </nav>\n");
      out.write("      </aside>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-12 col-lg-9 col-xl-10\">\n");
      out.write("      <div class=\"row g-4\">\n");
      out.write("        <div class=\"col-lg-7 col-xl-8\">\n");
      out.write("          <div class=\"card admin-card\">\n");
      out.write("            <div class=\"card-header fw-semibold\">Add New Service</div>\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <form id=\"adminServiceForm\" class=\"form-shell\" method=\"post\" action=\"");
      out.print( c );
      out.write("/services\" enctype=\"multipart/form-data\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"add\" />\n");
      out.write("\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                  <div class=\"form-section-title\">Basic Information</div>\n");
      out.write("                  <div class=\"mb-2\">\n");
      out.write("                    <label class=\"admin-label\">Title</label>\n");
      out.write("                    <input class=\"form-control form-control-sm\" name=\"title\" placeholder=\"Plumbing Service\" required>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"row g-2\">\n");
      out.write("                    <div class=\"col-12 col-md-6\">\n");
      out.write("                      <label class=\"admin-label\">Code <span class=\"admin-help\">(optional)</span></label>\n");
      out.write("                      <input class=\"form-control form-control-sm\" name=\"code\" placeholder=\"PLUMBING\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-md-6\">\n");
      out.write("                      <label class=\"admin-label\">Base Price</label>\n");
      out.write("                      <input class=\"form-control form-control-sm\" name=\"basePrice\" placeholder=\"From 299\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mt-2\">\n");
      out.write("                    <label class=\"admin-label\">Description</label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"description\" rows=\"3\" placeholder=\"Short service description\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                  <div class=\"form-section-title\">Pricing & Scope</div>\n");
      out.write("                  <div class=\"mb-2\">\n");
      out.write("                    <label class=\"admin-label\">Price Detail <span class=\"admin-help\">(optional)</span></label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"priceDetail\" rows=\"2\" placeholder=\"Final price depends on job scope and location.\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mb-2\">\n");
      out.write("                    <label class=\"admin-label\">What we'll do for you <span class=\"admin-help\">(optional, one line per point)</span></label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"weProvide\" rows=\"3\" placeholder=\"Inspection and scope confirmation&#10;Basic service delivery\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mb-0\">\n");
      out.write("                    <label class=\"admin-label\">What we need from user side <span class=\"admin-help\">(optional, one line per point)</span></label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"fromYou\" rows=\"3\" placeholder=\"Share exact requirement and preferred timing\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-section\">\n");
      out.write("                  <div class=\"form-section-title\">Service Experience</div>\n");
      out.write("                  <div class=\"mb-2\">\n");
      out.write("                    <label class=\"admin-label\">Usually not included <span class=\"admin-help\">(optional, one line per point)</span></label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"notIncluded\" rows=\"3\" placeholder=\"Material costs and heavy rework are charged separately\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"mb-0\">\n");
      out.write("                    <label class=\"admin-label\">Visit Steps <span class=\"admin-help\">(optional, one line per step)</span></label>\n");
      out.write("                    <textarea class=\"form-control form-control-sm\" name=\"visitSteps\" rows=\"3\" placeholder=\"Book the service&#10;Admin/pro confirms availability&#10;Service is delivered\"></textarea>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-section mb-0\">\n");
      out.write("                  <div class=\"form-section-title\">Media</div>\n");
      out.write("                  <label class=\"admin-label\">Image</label>\n");
      out.write("                  <input type=\"file\" class=\"form-control form-control-sm\" name=\"image\" accept=\"image/*\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button id=\"addServiceBtn\" class=\"btn btn-admin-primary btn-sm w-100 mt-2\" type=\"submit\">Add Service</button>\n");
      out.write("                <div class=\"save-hint\">Service will be visible on user portal immediately after save.</div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"alert alert-info mt-3 small mb-0\">\n");
      out.write("            Added services are saved and visible on user portal/API.\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-lg-5 col-xl-4\">\n");
      out.write("          <div class=\"card admin-card\">\n");
      out.write("            <div class=\"card-header fw-semibold\">Service List</div>\n");
      out.write("            <div class=\"table-responsive\">\n");
      out.write("              <table class=\"table table-sm table-hover align-middle mb-0 admin-table\">\n");
      out.write("                <thead class=\"table-light\">\n");
      out.write("                <tr>\n");
      out.write("                  <th>Code</th>\n");
      out.write("                  <th>Title</th>\n");
      out.write("                  <th>Base Price</th>\n");
      out.write("                  <th>Image</th>\n");
      out.write("                  <th>Description</th>\n");
      out.write("                  <th></th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/admin-services.jsp(326,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setVar("s");
      // /WEB-INF/jsp/admin-services.jsp(326,16) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin-services.jsp(326,16) '${services}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${services}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("              <tr>\n");
            out.write("                <td class=\"fw-semibold\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\n");
            out.write("                <td>");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\n");
            out.write("                <td>");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\n");
            out.write("                <td>\n");
            out.write("                  ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("\n");
            out.write("                </td>\n");
            out.write("                <td class=\"small\">");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return;
            out.write("</td>\n");
            out.write("                <td class=\"text-end\">\n");
            out.write("                  <form class=\"delete-service-form\" method=\"post\" action=\"");
            out.print( c );
            out.write("/services\">\n");
            out.write("                    <input type=\"hidden\" name=\"action\" value=\"delete\">\n");
            out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"service-id\">\n");
            out.write("                    <button type=\"submit\" class=\"btn btn-sm btn-outline-danger\">Delete</button>\n");
            out.write("                  </form>\n");
            out.write("                </td>\n");
            out.write("              </tr>\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager());
      out.write("\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("              </table>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("  (function () {\n");
      out.write("    var form = document.getElementById('adminServiceForm');\n");
      out.write("    if (form) {\n");
      out.write("      form.addEventListener('submit', function (e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        var btn = document.getElementById('addServiceBtn');\n");
      out.write("        if (btn) {\n");
      out.write("          btn.disabled = true;\n");
      out.write("          btn.textContent = 'Saving...';\n");
      out.write("        }\n");
      out.write("        var fd = new FormData(form);\n");
      out.write("        fetch('");
      out.print( c );
      out.write("/api/admin/services', {\n");
      out.write("          method: 'POST',\n");
      out.write("          body: fd,\n");
      out.write("          credentials: 'same-origin'\n");
      out.write("        })\n");
      out.write("          .then(function (r) { return r.json(); })\n");
      out.write("          .then(function (body) {\n");
      out.write("            if (!body || !body.ok) {\n");
      out.write("              throw new Error((body && body.error) ? body.error : 'Unable to add service');\n");
      out.write("            }\n");
      out.write("            window.location.reload();\n");
      out.write("          })\n");
      out.write("          .catch(function (err) {\n");
      out.write("            alert(err.message || 'Unable to add service');\n");
      out.write("          })\n");
      out.write("          .finally(function () {\n");
      out.write("            if (btn) {\n");
      out.write("              btn.disabled = false;\n");
      out.write("              btn.textContent = 'Add Service';\n");
      out.write("            }\n");
      out.write("          });\n");
      out.write("      });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    document.querySelectorAll('.delete-service-form').forEach(function (delForm) {\n");
      out.write("      delForm.addEventListener('submit', function (e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        var idField = delForm.querySelector('.service-id');\n");
      out.write("        var serviceId = idField ? idField.value : '';\n");
      out.write("        if (!serviceId) {\n");
      out.write("          return;\n");
      out.write("        }\n");
      out.write("        fetch('");
      out.print( c );
      out.write("/api/admin/services?id=' + encodeURIComponent(serviceId), {\n");
      out.write("          method: 'DELETE',\n");
      out.write("          credentials: 'same-origin'\n");
      out.write("        })\n");
      out.write("          .then(function (r) { return r.json(); })\n");
      out.write("          .then(function (body) {\n");
      out.write("            if (!body || !body.ok) {\n");
      out.write("              throw new Error((body && body.error) ? body.error : 'Unable to delete service');\n");
      out.write("            }\n");
      out.write("            window.location.reload();\n");
      out.write("          })\n");
      out.write("          .catch(function (err) {\n");
      out.write("            alert(err.message || 'Unable to delete service');\n");
      out.write("          });\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin-services.jsp(328,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.code}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin-services.jsp(329,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.title}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin-services.jsp(330,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.priceLabel}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin-services.jsp(332,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty s.imageDataUrl}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                    <img class=\"service-img\" src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.imageDataUrl}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" alt=\"service\">\n");
        out.write("                  ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/jsp/admin-services.jsp(336,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.summary}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/admin-services.jsp(346,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty services}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                  <tr>\n");
        out.write("                    <td colspan=\"6\" class=\"empty-state\">No services added yet. Add your first service using the form.</td>\n");
        out.write("                  </tr>\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager());
    return false;
  }
}
