/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.16
 * Generated at: 2026-04-08 10:06:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_002dusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1664453510000L));
    _jspx_dependants.put("jar:file:/Users/tryeno_team/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 final String c = request.getContextPath(); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Admin - User Management</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    :root { --admin-primary: #5a67d8; --admin-accent: #7c3aed; }\n");
      out.write("    body { background: #f3f5fb; }\n");
      out.write("    .admin-shell { min-height: 100vh; }\n");
      out.write("    .sidebar {\n");
      out.write("      background: #111827;\n");
      out.write("      color: #cbd5e1;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      padding: 1rem;\n");
      out.write("      position: sticky;\n");
      out.write("      top: 1rem;\n");
      out.write("      min-height: calc(100vh - 2rem);\n");
      out.write("      box-shadow: 0 16px 28px rgba(2, 6, 23, 0.2);\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("    .sidebar-title { color: #f8fafc; font-weight: 700; font-size: 0.95rem; margin-bottom: 0.75rem; }\n");
      out.write("    .sidebar .nav-link {\n");
      out.write("      color: #cbd5e1; border-radius: 10px; padding: 0.55rem 0.7rem; margin-bottom: 0.2rem; font-size: 0.92rem;\n");
      out.write("      min-height: 52px; display: flex; align-items: center;\n");
      out.write("    }\n");
      out.write("    .sidebar .nav-link:hover { background: rgba(255,255,255,0.08); color: #fff; }\n");
      out.write("    .sidebar .nav-link.active {\n");
      out.write("      background: linear-gradient(135deg, var(--admin-primary), var(--admin-accent)); color: #fff; font-weight: 600;\n");
      out.write("    }\n");
      out.write("    .content-panel {\n");
      out.write("      height: calc(100vh - 2rem);\n");
      out.write("      overflow-y: auto;\n");
      out.write("      padding-right: 0.35rem;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container-fluid py-3 admin-shell\">\n");
      out.write("  <div class=\"row g-3\">\n");
      out.write("    <div class=\"col-lg-2\">\n");
      out.write("      <aside class=\"sidebar\">\n");
      out.write("        <div class=\"sidebar-title\">Admin Menu</div>\n");
      out.write("        <nav class=\"nav flex-column\">\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/dashboard\">Dashboard</a>\n");
      out.write("          <a class=\"nav-link active\" href=\"");
      out.print( c );
      out.write("/users\">User Management</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/services\">Service Add / Manage</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/reviews\">Reviews</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/settings\">Settings</a>\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( c );
      out.write("/logout\">Logout</a>\n");
      out.write("        </nav>\n");
      out.write("      </aside>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-lg-10 content-panel\">\n");
      out.write("      <h3>User Management</h3>\n");
      out.write("      <p id=\"userCountText\" class=\"text-muted mb-3\">Total users: 0</p>\n");
      out.write("      <div id=\"usersAlertWrap\"></div>\n");
      out.write("      <div class=\"table-responsive bg-white rounded border\">\n");
      out.write("        <table class=\"table table-sm mb-0\">\n");
      out.write("          <thead class=\"table-light\">\n");
      out.write("          <tr><th>ID</th><th>Name</th><th>Email</th><th>Phone</th><th>Role</th></tr>\n");
      out.write("          </thead>\n");
      out.write("          <tbody id=\"usersTableBody\">\n");
      out.write("          <tr><td colspan=\"5\" class=\"text-center text-muted py-3\">Loading users...</td></tr>\n");
      out.write("          </tbody>\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("  (function () {\n");
      out.write("    var userCountText = document.getElementById('userCountText');\n");
      out.write("    var usersAlertWrap = document.getElementById('usersAlertWrap');\n");
      out.write("    var usersTableBody = document.getElementById('usersTableBody');\n");
      out.write("\n");
      out.write("    function escapeHtml(value) {\n");
      out.write("      if (value === null || value === undefined) {\n");
      out.write("        return '';\n");
      out.write("      }\n");
      out.write("      return String(value)\n");
      out.write("        .replace(/&/g, '&amp;')\n");
      out.write("        .replace(/</g, '&lt;')\n");
      out.write("        .replace(/>/g, '&gt;')\n");
      out.write("        .replace(/\"/g, '&quot;')\n");
      out.write("        .replace(/'/g, '&#39;');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function renderRows(users) {\n");
      out.write("      if (!Array.isArray(users) || users.length === 0) {\n");
      out.write("        usersTableBody.innerHTML = '<tr><td colspan=\"5\" class=\"text-center text-muted py-3\">No users found.</td></tr>';\n");
      out.write("        return;\n");
      out.write("      }\n");
      out.write("      var html = '';\n");
      out.write("      users.forEach(function (u) {\n");
      out.write("        html += '<tr>' +\n");
      out.write("          '<td>' + escapeHtml(u.id) + '</td>' +\n");
      out.write("          '<td>' + escapeHtml(u.fullName) + '</td>' +\n");
      out.write("          '<td>' + escapeHtml(u.email) + '</td>' +\n");
      out.write("          '<td>' + escapeHtml(u.phone) + '</td>' +\n");
      out.write("          '<td>' + escapeHtml(u.role) + '</td>' +\n");
      out.write("          '</tr>';\n");
      out.write("      });\n");
      out.write("      usersTableBody.innerHTML = html;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function showAlert(type, message) {\n");
      out.write("      usersAlertWrap.innerHTML = '<div class=\"alert alert-' + type + '\">' + escapeHtml(message) + '</div>';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    fetch('");
      out.print( c );
      out.write("/api/admin/users', { credentials: 'same-origin' })\n");
      out.write("      .then(function (response) { return response.json(); })\n");
      out.write("      .then(function (data) {\n");
      out.write("        var count = data && typeof data.count === 'number' ? data.count : 0;\n");
      out.write("        userCountText.textContent = 'Total users: ' + count;\n");
      out.write("        renderRows(data && data.users ? data.users : []);\n");
      out.write("        if (!data || !data.ok) {\n");
      out.write("          showAlert('danger', (data && data.error) ? data.error : 'Unable to load users.');\n");
      out.write("          return;\n");
      out.write("        }\n");
      out.write("        if (data.dbConfigured === false) {\n");
      out.write("          showAlert('info', 'Running on local-file mode (DB not configured).');\n");
      out.write("          return;\n");
      out.write("        }\n");
      out.write("        usersAlertWrap.innerHTML = '';\n");
      out.write("      })\n");
      out.write("      .catch(function () {\n");
      out.write("        userCountText.textContent = 'Total users: 0';\n");
      out.write("        usersTableBody.innerHTML = '<tr><td colspan=\"5\" class=\"text-center text-muted py-3\">Unable to load users.</td></tr>';\n");
      out.write("        showAlert('danger', 'Unable to load users from API. Please try again.');\n");
      out.write("      });\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
