/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.16
 * Generated at: 2026-04-07 10:20:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 final String c = request.getContextPath(); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Admin Login - Easy 2 Work</title>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("      min-height: 100vh;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      padding: 20px;\n");
      out.write("    }\n");
      out.write("    .admin-login-card {\n");
      out.write("      background: white;\n");
      out.write("      border-radius: 15px;\n");
      out.write("      box-shadow: 0 10px 40px rgba(0,0,0,0.2);\n");
      out.write("      padding: 3rem;\n");
      out.write("      max-width: 450px;\n");
      out.write("      width: 100%;\n");
      out.write("    }\n");
      out.write("    .admin-title {\n");
      out.write("      color: #667eea;\n");
      out.write("      font-weight: 700;\n");
      out.write("      margin-bottom: 1.5rem;\n");
      out.write("    }\n");
      out.write("    .btn-admin-login {\n");
      out.write("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("      border: none;\n");
      out.write("      color: white;\n");
      out.write("      padding: 0.75rem;\n");
      out.write("      font-weight: 600;\n");
      out.write("      border-radius: 50px;\n");
      out.write("      transition: transform 0.2s;\n");
      out.write("    }\n");
      out.write("    .btn-admin-login:hover {\n");
      out.write("      transform: translateY(-2px);\n");
      out.write("      box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);\n");
      out.write("      color: white;\n");
      out.write("    }\n");
      out.write("    .form-control:focus {\n");
      out.write("      border-color: #667eea;\n");
      out.write("      box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"admin-login-card\">\n");
      out.write("    <div class=\"text-center mb-4\">\n");
      out.write("      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"60\" height=\"60\" fill=\"currentColor\" class=\"bi bi-shield-lock text-primary\" viewBox=\"0 0 16 16\">\n");
      out.write("        <path d=\"M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z\"/>\n");
      out.write("        <path d=\"M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z\"/>\n");
      out.write("      </svg>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h1 class=\"admin-title text-center\">Admin Portal</h1>\n");
      out.write("    <p class=\"text-center text-muted mb-4\">Restricted Access</p>\n");
      out.write("\n");
      out.write("    ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("        ");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form method=\"post\" action=\"");
      out.print( c );
      out.write("/login\">\n");
      out.write("      <div class=\"mb-3\">\n");
      out.write("        <label for=\"email\" class=\"form-label\">Email Address</label>\n");
      out.write("        <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required autofocus>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"mb-3\">\n");
      out.write("        <label for=\"password\" class=\"form-label\">Password</label>\n");
      out.write("        <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"d-grid mb-3\">\n");
      out.write("        <button type=\"submit\" class=\"btn btn-admin-login\">Sign In</button>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <hr class=\"my-4\">\n");
      out.write("\n");
      out.write("    <div class=\"text-center\">\n");
      out.write("      <p class=\"small text-muted mb-0\">\n");
      out.write("        Admin access only. Unauthorized access is prohibited.\n");
      out.write("      </p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
